
update status: None
error: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1467106062:AAEk636ObsO5PDSoJYhLc_1mZpu7MM9k0rA/getUpdates (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x00000203B0C03640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))